### ISSUE TITLE
Mesh animation while maintaing a smooth surface.

### ISSUE THREAD

**Issue by Davar1990** [LiangliangNan/Easy3D#104]
Thanks for your good luck wish in the closed issue https://github.com/LiangliangNan/Easy3D/issues/102

I spent quality time on this and made so much progress, as far as I could. Now I have hit a wall and I could really use your kind help. 
Basically, I created a `CustomViewer` class inheriting from the viewer class and added customized functions to simulate `Viwer::run()` . My goal is to animate the facial expressions of a 3D face mesh. In order to test my implementation, I tried switching back and forth between two expressions (open/closed mouth). The code is as follows and it runs successfully. 

```
CustomViewer viewer("mesh animation");
viewer.set_background_color(easy3d::vec4(0.6, 0.8, 0.8, 0.1));
easy3d::Camera* cam = viewer.camera();
cam->setUpVector(easy3d::vec3(0, 1, 0));
cam->setViewDirection(easy3d::vec3(0, 0, -1));

auto surface = new easy3d::TrianglesDrawable("faces");
surface->update_vertex_buffer(face1);
surface->update_element_buffer(indices);
surface->set_uniform_coloring(easy3d::vec4(0.8, 0.8, 0.8, 1.0));
viewer.add_drawable(surface);

viewer.initialize();
GLFWwindow* window = viewer.getWindow();

while (true) {

	//=============== face 1 (closed mouth)
	surface->update_vertex_buffer(face1);
	viewer.custom_draw();
	glfwSwapBuffers(window);
	std::this_thread::sleep_for(std::chrono::milliseconds(static_cast<int>(200)));

	//=============== face 2 (open mouth)
	surface->update_vertex_buffer(face2);
	viewer.custom_draw();
	glfwSwapBuffers(window);
	std::this_thread::sleep_for(std::chrono::milliseconds(static_cast<int>(200)));

	glfwPollEvents();

	if (glfwWindowShouldClose(window) || viewer.should_exit()) {
		viewer.custom_cleanup();
		break;
	}

}

glfwTerminate();
return EXIT_SUCCESS;
```
My facial mesh has quads not triangles but I transformed the indices for triangles by rearranging them as `v0, v1, v2, v2, v3, v0`.

Here's the result
https://drive.google.com/file/d/19h8W-mqHV2GZhNI704I3sjcPZVjiOi7d/view?usp=sharing

But my end goal is to achieve the same with smooth surface for which I'm building the `SurfaceMesh` with QUADS, not triangles as follows.

```
easy3d::SurfaceMesh* mesh = new easy3d::SurfaceMesh();
vector<easy3d::SurfaceMesh::Vertex> surfaceVertices(face1.size());
for (int i = 0; i < face1.size(); i++)
	surfaceVertices[i] = mesh->add_vertex(face1[i]);
for (int i = 0; i < _quads.size(); i++) {
	mesh->add_quad(
		surfaceVertices[_quads[i][0]], 
		surfaceVertices[_quads[i][1]], 
		surfaceVertices[_quads[i][2]], 
		surfaceVertices[_quads[i][3]]);
}
viewer.add_model(mesh);        
auto surface = mesh->renderer()->get_triangles_drawable("faces");  
surface->set_smooth_shading(true);
surface->set_uniform_coloring(easy3d::vec4(0.8, 0.8, 0.8, 1.0));
```
![smooth_shade](https://user-images.githubusercontent.com/17028943/146320844-4bd8b64f-6157-49ad-a3dd-9ecdbf85162e.PNG)

So in the original implementation, I replaced the following section by the one above and ran the animation again. 

```
auto surface = new easy3d::TrianglesDrawable("faces");
surface->update_vertex_buffer(face1);
surface->update_element_buffer(indices);
surface->set_uniform_coloring(easy3d::vec4(0.8, 0.8, 0.8, 1.0));
viewer.add_drawable(surface);
```
First I tried `surface->set_smooth_shading(true);`
https://drive.google.com/file/d/1yI1gz74lL2NAqS1bB4CxnLQPITIBtC9G/view?usp=sharing

Then I tried `surface->set_smooth_shading(false);`
https://drive.google.com/file/d/1kAhxA-1Hs-ZxJYC3Qw9Dw5rD05I9CCGj/view?usp=sharing

Even though I can compute the normals myself, it would be ideal if I could achieve the end goal leaving the normals computation up to the library itself. I tried my best to figure out how I could fix this issue but now I feel I have hit a wall. I would very much appreciate your help.

**Comment by LiangliangNan** [comment]
Always glad to help, and to see how Easy3D is used by others :-)

I believe the reason is: your element buffer "indices" is not identical to that constructed by Easy3D. 
Specifically, the element buffer for the “good” smooth drawable is constructed by Easy3D using the built-in Tessellator, while when you create your own element indices you use another approach. The two approaches usually do not produce the same triangulation. This leads to a wrong index buffer.

The easiest way (and also for the best performance) to fix it, is to have two individual meshes (one for the closed mouth and the other for the open mouth).
You use `viewer.add_model()` twice to add the two meshes to the viewers.
During the rendering, you repeatedly hide one and show the other by calling the `set_visible(bool)` method of both drawable.
This has a performance benefit: you can avoid updating the buffers (especially when you have large models).
I do recommend this solution.

Of course, you can use only one mesh with only one surface and repeatedly update the buffers. Do make sure you use the same method to generate the index buffer data for both drawables. This approach requires (a little bit) diving into the library and it also has the performance overhead. So I don't recommend this.

**Comment by Davar1990** [comment]
I appreciate your help :)

Unfortunately, I don't have only one or two expressions to switch between them. I have some predefined expression blendshapes and at any frame, the resultant expression would be the linear combination of all those blendshape meshes. So there are infinite number of ways the vertices can change in creating a new expression. 

There's also another thing I was originally thinking to do, and that's building the SurfaceMesh from scratch in the `while loop` but that's not optimized as I should constantly allocate and deallocate the new space for the resultant expression mesh. Considering the fact that indices will always remain the same, and the only things that change are the vertices and the associated normals, I believe the best way to approach this task is to only update the vertices (the normals will be handled by the library internally). Is my assumption correct?

If the best way is to "use only one mesh with only one surface and repeatedly update the buffers", is there a section in the library you could point me to, for a quick head start? I will delve deep and try to gain the required understanding. 

Please also note that I extract the indices from the face section ("f") of the ".obj" file associated with one of the predefined expression blendshape meshes. All the blendshapes have the same visualization parameters. 

`f 2303/9463/0 7608/9470/0 9603/9471/0 7498/9464/0`

**Comment by LiangliangNan** [comment]
Now I understand what is actually needed and the solution is quite simple.

**Why it doesn't work now?**
Easy3D tries to remove duplicated vertices (so as to minimize the number of points sent to GPU). The Tessellator class is used for this purpose.  It triangulates the surface and generates vertex indices for each triangle.  
Because duplicated vertices are removed and the triangulation might be different from the way you split quads into triangles. yours, the vertex indices may not correspond to the original vertex indices anymore. This results in the currently incorrect visualization.

**Solution?**
(I assume the meshes have the same number of vertices and perfect one-to-one vertex correspondences).
Use triangle meshes instead of quad meshes. This way the vertex indices are always fixed.
To efficiently update the vertex data in GPU, you can map the vertex buffer and obtain a pointer to the GPU memory. Then you can directly modify the vertex coordinates in GPU.  Below is code the below:
```c++
        // map the vertex buffer into the client's address space. 
        // then the GPU memory can be treated as normal RAM memory. So any memory manipulation function 
        // such as `memcpy(...)` can be used.
        void* pointer = VertexArrayObject::map_buffer(GL_ARRAY_BUFFER, surface->vertex_buffer(), GL_WRITE_ONLY);

        vec3* vertices = reinterpret_cast<vec3*>(pointer);
        if (!vertices) // just in case the mapping failed
            return false;

        for (std::size_t i=0; i<points.size(); ++i)  
            vertices[i] = new_XYZ[i];   // replace new_XYZ by the name of the array storing the new points

        // unmap the vertex buffer
        VertexArrayObject::unmap_buffer(GL_ARRAY_BUFFER, surface->vertex_buffer());

        viewer.update();
```

**Further optimization?**
The above code rewrites ALL vertex coordinates, which can be replaced by a single call to the `memcpy(...)` function.
Since the animation is partial, so can update the coordinates and normals for only those deformed. But this requires knowing the indices of the changed vertices.

**Comment by Davar1990** [comment]
It got fixed :) 
https://drive.google.com/file/d/1ehjU4ZdWVZDKOhIUVTdO18srvT1C2Tt8/view?usp=sharing

Thank you very much for kindly taking the time to address this issue in such detail. The trick, as you mentioned, was to change the quad mesh to triangle mesh by replacing `mesh->add_quad( v0, v1, v2, v3);` to 

```
mesh->add_triangle(v0, v1, v2);
mesh->add_triangle(v2, v3, v0);
```
and then adding the lines you shared for updating the normal and element buffers. So the overall code looks as follows. 

```
CustomViewer viewer("mesh animation");
viewer.set_background_color(easy3d::vec4(0.6, 0.8, 0.8, 0.1));
easy3d::Camera* cam = viewer.camera();
cam->setUpVector(easy3d::vec3(0, 1, 0));
cam->setViewDirection(easy3d::vec3(0, 0, -1));

easy3d::SurfaceMesh* mesh = new easy3d::SurfaceMesh();
vector<easy3d::SurfaceMesh::Vertex> surfaceVertices(face1.size());
for (int i = 0; i < face1.size(); i++)
	surfaceVertices[i] = mesh->add_vertex(face1[i]);
for (int i = 0; i < _quads.size(); i++) {
	mesh->add_triangle(surfaceVertices[_quads[i][0]], surfaceVertices[_quads[i][1]], surfaceVertices[_quads[i][2]]);
	mesh->add_triangle(surfaceVertices[_quads[i][2]], surfaceVertices[_quads[i][3]], surfaceVertices[_quads[i][0]]);
}

mesh->update_vertex_normals();
auto normals = mesh->get_vertex_property<easy3d::vec3>("v:normal");

std::vector<unsigned int> d_indices;
d_indices.reserve(mesh->n_faces() * 3);
for (auto face : mesh->faces()) {
	for (auto h : mesh->halfedges(face))
		d_indices.push_back(mesh->target(h).idx());
}

viewer.add_model(mesh);

auto drawable = mesh->renderer()->get_triangles_drawable("faces");
drawable->update_element_buffer(d_indices);
drawable->update_normal_buffer(normals.vector());
drawable->set_smooth_shading(true);

viewer.initialize();
GLFWwindow* window = viewer.getWindow();

while (true) {

	//=============== face 1
	drawable->update_vertex_buffer(face1);
	viewer.custom_draw();
	glfwSwapBuffers(window);
	std::this_thread::sleep_for(std::chrono::milliseconds(static_cast<int>(200)));

	//=============== face 2
	drawable->update_vertex_buffer(face2);
	viewer.custom_draw();
	glfwSwapBuffers(window);
	std::this_thread::sleep_for(std::chrono::milliseconds(static_cast<int>(200)));

	glfwPollEvents();

	if (glfwWindowShouldClose(window) || viewer.should_exit()) {
		viewer.custom_cleanup();
		break;
	}

}

glfwTerminate();
return EXIT_SUCCESS;
```
The convenience of using this library and the way it's being maintained is impressive. Thanks for creating Easy3D :)

**Comment by LiangliangNan** [comment]
Very glad the problem has been solved.
Since you may have infinite intermediate expressions, a smooth animation might be desired. In this case, you can have a look at Tutorial_311_Animation.

I will close this issue. Please feel free to re-open it when necessary.
Good luck with your research!
