### ISSUE TITLE
ImGui::InputText does not work in the Tutorial_201_Viewer_imgui

### ISSUE THREAD

**Issue by alexxlzhou** [LiangliangNan/Easy3D#111]
Hi there,

I am trying out the viewer imgui example and want to add an inputtext field in the ViewerImGui::post_draw() as following: 
       ...
        ImGui::PopStyleVar();

        {
            ImGui::Begin("Hello, world!");                          // Create a window called "Hello, world!" and append into it.
            static char buff[128] = "any";
            ImGui::InputText("label", buff, 128);
            ImGui::End();
        }

	ImGui::Render();
...

However, the InputText will not accept any input to change the text.
Any idea why?
Thank you!

Alex

**Comment by LiangliangNan** [comment]
This is due to that the callbacks functions are not enabled by default, which can be solved by switching the second argument in `ImGui_ImplGlfw_InitForOpenGL(...)` from `false` to `true`, i.e., 

    change
 			`ImGui_ImplGlfw_InitForOpenGL(window_, false);`   - line 78 in Tutorial_201_Viewer_imgui/viewer.cpp
    to
			`ImGui_ImplGlfw_InitForOpenGL(window_, true);`

I've implemented this change in the code.
Thanks for reporting this issue!

**Comment by alexxlzhou** [comment]
Good, thanks for quick response!
