### ISSUE TITLE
WGL: Failed to make context current: The requested transformation operation is not supported.

### ISSUE THREAD

**Issue by petrasvestartas** [LiangliangNan/Easy3D#119]
Hi,

Sometimes I get this error:
GLFW error 65544: WGL: Failed to make context current: The requested transformation operation is not supported.

I can still preview the geometry, but do you know what is causing that?
This is the screenshot:
![image](https://user-images.githubusercontent.com/18013985/167271065-721cdfce-2fdf-447c-9f09-42cea144a610.png)

**Comment by LiangliangNan** [comment]
Please provide information that is useful for figuring out the issue, e.g, 
 - operating system name and version (e.g. Windows 10 64bit or Ubuntu 18.10);
 - GPU and driver version;
 - Easy3D release version (e.g., 2.4.3) if you are using an official release of Easy3D, Otherwise, the Easy3D commit ID (e.g.
06d1dfe55a5eec2d4b650041cb529f5efdeadd31) from Git;
 - a short and self-contained code example that can produce the issue. Just put it inline in the body text. If the bug is reproducible with one of the test programs or examples that come with Easy3D, simply mention that instead;
 - the full log file (or the full console output from the console window).

For more details on what information is necessary to resolve different bugs/issues:
https://github.com/LiangliangNan/Easy3D/blob/main/CONTRIBUTING.md
