### ISSUE TITLE
CMake ExternalProject

### ISSUE THREAD

**Issue by petrasvestartas** [LiangliangNan/Easy3D#123]
Hi,

Do you have an example how to download Easy3D with main dependencies such as ImGUI using ExternalProject option in CMake?
The reason to ask is that I already downloading multiple libraries in my project using so called superbuild  methods when external libraries are downloaded from github and linked to one exe.

Currently I can download easy3d like this:
```
set(CMAKE_CXX_STANDARD 11)                        # specify C++ standard
find_package(Easy3D REQUIRED)                     # request Easy3D 
target_link_libraries(YOUR_APP_NAME easy3d::core) # request necessary Easy3D modules (add more if needed, e.g., viewer, algo)
```

But I want to automate the downloading and linking process directly in one CMake similarly I do with Eigen libary:
```



########################################################################
#PROJECT INTIALIZATION
########################################################################
project(superbuild LANGUAGES CXX)
cmake_minimum_required(VERSION 3.19)

########################################################################
# START SUPERBUILD
########################################################################

SET(GET_LIBS "" CACHE STRING "Set option to download dependencies")
include(ExternalProject)

########################################################################
# EIGEN
########################################################################
SET(GET_LIBS "" CACHE STRING "Set option to download dependencies")
if (GET_LIBS)
  message(AUTHOR_WARNING "GET_LIBS_" ${GET_LIBS})
  ExternalProject_Add(eigen
    GIT_REPOSITORY https://gitlab.com/libeigen/eigen.git
    GIT_TAG 3.4.0
    CMAKE_ARGS
      -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
      -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
      -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/install/eigen #has not effect
    SOURCE_DIR   "${CMAKE_BINARY_DIR}/install/eigen" #install directory is in build/install/eigen
    BUILD_COMMAND "" #do not build
    INSTALL_COMMAND "" #do not install
  )

endif ()

###############################################################################
#EXECUTABLE THANK LINK HEADER ONLY DIRECTORY
###############################################################################
SET(BUILD_MY_PROJECTS "" CACHE STRING "Build Project")
if (BUILD_MY_PROJECTS)
  add_executable(my_exe main.cpp)
  target_include_directories(my_exe PRIVATE "${CMAKE_BINARY_DIR}/install/eigen/") #add directory of the EIGEN header-only library 
endif ()

```

**Comment by LiangliangNan** [comment]
No need to download any extra libraries for Easy3D.
All the dependencies are already included in the distribution of Easy3D (see the `3rd_party` subdirectory).

**Comment by petrasvestartas** [comment]
@LiangliangNan  It is not a question about 3d parties.
I would like to ask how can I downalod easy3d using external project and link it my executable with CMake?

**Comment by LiangliangNan** [comment]
See the "[Use Easy3D in your project](https://github.com/LiangliangNan/Easy3D#use-easy3d-in-your-project)" section of the ReadMe file.

**Comment by petrasvestartas** [comment]
I already did, this only works if the repository is cloned in advanced, built and installed.

I would like to ask how the cloning, building and installing can be done using CMake only, without manually cloning the repository?

**Comment by LiangliangNan** [comment]
Now I got your questions :-)
See the answers below.

> I already did, this only works if the repository is cloned in advance, built and installed.
> I would like to ask how the cloning, building and installing can be done using CMake only, without manually cloning the repository?
I am afraid one always has to download the code ("clone" is also ok but not necessary) and build Easy3D on a new machine before it can be linked to another program. This only needs to be done once on a machine.

The "download" command (I guess `FetchContent_Declare` but never used it before) can also be written into the CMake script and the actual downloading will be executed during CMaking the project, but I really don't think it is necessary, so I prefer to keep this traditional way for Easy3D.

I also believe this is more of a task for projects that use Easy3D (and not for Easy3D itself) :-)
Moreover, having this automation may result in downloading Easy3D multiple times if several projects requires Easy3D.


> The building process is very slow, since I do not need by default examples, I just want to link to my exe.
Indeed, building everything is slow. To avoid building the examples, you can set `EASY3D_BUILD_TUTORIALS` to `OFF`.

> Also for some reason the find_package does not seam to work. Shouldn't cmake files be detected automatically?
> ```
>   Add the installation prefix of "Easy3D" to CMAKE_PREFIX_PATH or set        
>   "Easy3D_DIR" to a directory containing one of the above files.  If "Easy3D"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> ```
This is expected because a project never automatically knows in which folder a user has downloaded Easy3D, so one has to set the `build` path of Easy3D.

**Comment by LiangliangNan** [comment]
I saw you requested only `easy3d::core`, because you need the viewer, so you should link to `easy3d::viewer`.
So 
target_link_libraries(my_exe easy3d::viewer)

(the following are not errors, but good to know)
It is not a good idea to hard-code the path to easy3d by changing the CMake list file. You can do this in the CMake cache files. This will ensure the same CMake list file work for all your collaborators.
Besides, you can remove the two lines with`target_include_directories`.

**Comment by petrasvestartas** [comment]
It works. Thank you so much.

I would like to use "imgui" with visualization of some geometry like pointscloud, lines and meshes.
In such case what should I add here, since I think easy3d::viewer would not be enough:
`target_link_libraries(my_exe easy3d::viewer)`

**Comment by LiangliangNan** [comment]
I think you need to add imgui. 
Easy already has an example showing how to use imgui: https://github.com/LiangliangNan/Easy3D/tree/main/tutorials/Tutorial_201_Viewer_imgui

**Comment by petrasvestartas** [comment]
I linked imgui like this:
`target_link_libraries(my_exe 3rd_imgui easy3d::core easy3d::renderer easy3d::viewer easy3d::util) `

This gives me error for not finding header files of imgui.
What directory I need to set or what property I need to set to resolve this error?

```
C:\IBOIS57\_Code\Software\CPP\CMAKE\super_build\example_easy3d\manual_download\Easy3D\3rd_party/imgui/backends/imgu
i_impl_glfw.h(21,10): fatal error C1083: Cannot open include file: 'imgui.h': No such file or directory [C:\IBOIS57 
\_Code\Software\CPP\CMAKE\super_build\example_easy3d\build\my_exe.vcxproj]
```

**Comment by LiangliangNan** [comment]
You need to call ‘target_include_directories’ to specify the include directory to imgui.

**Comment by petrasvestartas** [comment]
I wrote this:
`target_include_directories(my_exe PUBLIC "C:/IBOIS57/_Code/Software/CPP/CMAKE/super_build/example_easy3d/manual_download/Easy3D/3rd_party/imgui/")
`
Now it ask for imgui lib:

```
LINK : fatal error LNK1104: cannot open file '3rd_imgui.lib' [C:\IBOIS57\_Code\Software\
CPP\CMAKE\super_build\example_easy3d\build\my_exe.vcxproj]
```

How would you link this file in CMakeLists.txt ? 

![image](https://user-images.githubusercontent.com/18013985/175827694-052157c1-365d-432f-9557-ac4e13721f0c.png)

**Comment by LiangliangNan** [comment]
Use the full path name of the lib (e.g., "C:/dev/libs/3rd_imgui.lib"), instead of only "3rd_imgui.lib".
Okay, now your questions are more about the use of CMake, but not related to Easy3D, so I am closing this issue now.
Feel free to reopen it there are issues with the use of Easy3D.

**Comment by petrasvestartas** [comment]
It still feels like Easy3D issue.

Why do I need to specify the full directory?

Is there a way to set the library directory the same way as is done here?
`set(Easy3D_DIR "C:/IBOIS57/_Code/Software/CPP/CMAKE/super_build/example_easy3d/manual_download/Easy3D/Release")  ` 

Is there a specific keyword for imgui like **Easy3D_DIR**


my full code:
```cmake

# create executable
add_executable(my_exe main.cpp viewer.cpp viewer.h)

# set Easy3D directory
set(Easy3D_DIR "C:/IBOIS57/_Code/Software/CPP/CMAKE/super_build/example_easy3d/manual_download/Easy3D/Release")   

#link cmake config of Easy3D
include( "C:/IBOIS57/_Code/Software/CPP/CMAKE/super_build/example_easy3d/manual_download/Easy3D/Release/Easy3DConfig.cmake")

#link easy3D
find_package(Easy3D REQUIRED) 

#link IMGUI headers
target_include_directories(my_exe PUBLIC "C:/IBOIS57/_Code/Software/CPP/CMAKE/super_build/example_easy3d/manual_download/Easy3D/3rd_party/imgui/")

#link library to EXE
target_link_libraries(my_exe 
"C:/IBOIS57/_Code/Software/CPP/CMAKE/super_build/example_easy3d/manual_download/Easy3D/Release/lib/Release/3rd_imgui.lib" 
easy3d::core easy3d::renderer easy3d::viewer easy3d::util) # request necessary Easy3D modules (add more if needed, e.g., viewer, algo)
```

**Comment by LiangliangNan** [comment]
In principle, one has to specify the path for EVERY library when using it.
The good thing is that many libraries have handled this internally. For example in Easy3D, the `renderer` module depends on `3rd_glew`, and thus Easy3D explicitly exports this information in `Easy3DConfig.cmake`. By doing so, `3rd_glew` is automatically accessible to projects where the `renderer` is already found.

imgui is not because no Easy3D module depends on it.

Again, this is a general programming question and also the use of CMake, and it is not Easy3D related.
