### ISSUE TITLE
Issue related to the previous one

### ISSUE THREAD

**Issue by petrasvestartas** [LiangliangNan/Easy3D#124]
_I prefer to discuss this in the previous issue. But I do not know how to reopen it._ 

It still feels like Easy3D issue, because I do not know what are the CMake variables in Easy3D project.
Is there a way to set the library directory the same way as is done here?
`set(Easy3D_DIR "C:/IBOIS57/_Code/Software/CPP/CMAKE/super_build/example_easy3d/manual_download/Easy3D/Release")  ` 
For examplem, is there a specific keyword for imgui like **Easy3D_DIR** ?

my full code:
```cmake

# create executable
add_executable(my_exe main.cpp viewer.cpp viewer.h)

# set Easy3D directory
set(Easy3D_DIR "C:/IBOIS57/_Code/Software/CPP/CMAKE/super_build/example_easy3d/manual_download/Easy3D/Release")   

#link cmake config of Easy3D
include( "C:/IBOIS57/_Code/Software/CPP/CMAKE/super_build/example_easy3d/manual_download/Easy3D/Release/Easy3DConfig.cmake")

#link easy3D
find_package(Easy3D REQUIRED) 

#link IMGUI headers
target_include_directories(my_exe PUBLIC "C:/IBOIS57/_Code/Software/CPP/CMAKE/super_build/example_easy3d/manual_download/Easy3D/3rd_party/imgui/")

#link library to EXE
target_link_libraries(my_exe 
"C:/IBOIS57/_Code/Software/CPP/CMAKE/super_build/example_easy3d/manual_download/Easy3D/Release/lib/Release/3rd_imgui.lib" 
easy3d::core easy3d::renderer easy3d::viewer easy3d::util) # request necessary Easy3D modules (add more if needed, e.g., viewer, algo)
```

**Comment by LiangliangNan** [comment]
In principle, one has to specify the path for EVERY library when using it.
The good thing is that many libraries have handled this internally. For example in Easy3D, the `renderer` module depends on `3rd_glew`, and thus Easy3D explicitly exports this information in `Easy3DConfig.cmake`. By doing so, `3rd_glew` is automatically accessible to projects where the `renderer` is already found.

`imgui` is not because no Easy3D module depends on it. 

Again, this is a general programming question and also the use of CMake, and it is not Easy3D related.
