### ISSUE TITLE
Property transfer during surface mesh editing

### ISSUE THREAD

**Issue by meiyy** [LiangliangNan/Easy3D#137]
Seems that `SurfaceMesh` does not maintain the properties of face or edge, during mesh editing operations like face `split`.
Is this intentionally designed or just not implemented?
Thanks.

**Comment by LiangliangNan** [comment]
This is intended. Because `SurfaceMesh` does not know (in most cases) how a property should be maintained during editing.
For example, when one splits a face by inserting a new vertex in the face, it is not clear how to assign the new vertex a color, or other properties. Of course, one can do linear interpolation, but this may not be desired by the user.
So I believe this should be handled by the client code.
If you have some good ideas, I'd be happy for discussion.

**Comment by meiyy** [comment]
What you said makes sense, though I still think, an option like `bool copy_on_split` on a specific face property is useful, and a default value `=false` can make old code unaffected.
As for myself, I just want to maintain the segmentation property on faces, and simply copy the property from the source faces is enough. 
If you think this is not a good idea, just forget about it, it seems less complex to maintain the prop than I thought.
But I suggest describing the relationship between new elements (like `h0,t1,f0,f1,f2,f3`) and the old ones in detail, maybe this will help the new users.

**Comment by LiangliangNan** [comment]
Thanks for the thoughts. I actually tried something similar to your idea, but it wasn't easy to come up with an idea to handle properties for different element types (vertices, edges, faces), and all kinds of properties. 

>  ...the relationship between new elements (like h0,t1,f0,f1,f2,f3) and the old ones

Indeed, it is not clear what the new faces are. I will think about it and (may, if possible) add a few sentences to the function explanation. But for now, you can simply assign all faces (incident to the new vertex) the same property as the old face's.

I am closing this issue, please feel free to re-open it if you have any questions/suggestions.
