### ISSUE TITLE
Ambient occlusion crashes on non-manifold models & provide *real* ground for shadows

### ISSUE THREAD

**Issue by yvanblanchard** [LiangliangNan/Easy3D#155]
hello,

how to activate/switch rendering mode in MAPPLE app, and in particular to set ambient occlusion and soft shadows ?

Moreover, I tried to compile the example/tutorial dedicated to ambient occlusion test, but I can't compile the easy3d libs. I get some compiler errors in 'Utils' (console_style.cpp, `"s << console::styles[style];`")
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0349	no operator "<<" matches these operands	easy3d_util	C:\YVAN\Customers\3DPrint\Easy3D-main\easy3d\util\console_style.cpp	146	
```
I'm using VS2017 with Win10 x64 (with QT5).

Thank you

**Comment by LiangliangNan** [comment]
The SSAO and shadow (and a few other effects) can be switched on through the *Global* rendering panel. See below:
![image](https://user-images.githubusercontent.com/15526536/226836936-cd502aa1-cd4d-412f-b0cb-5a60ecf4e16a.png)


The compiler error is quite strange because `s << console::styles[style];` simply outputs a `std::string`.
Can you try adding `#include <string>` at the beginning of console_style.cpp and see if the same error still occurs? 
(normally <cstring> has already included <string.h> and thus it can be avoided)
If the same error still exists, please post your entire compile log here (the error might be caused by something else)

**Comment by yvanblanchard** [comment]
Thank you.

I tried the shadow mode, but it looks strange that the shadow does not lie on the XY plane by default ? Is it possible to control it ?
![image](https://user-images.githubusercontent.com/63931618/226842540-30308b84-eef9-4a0b-bef4-0fd167ef9426.png)

Moreover, I tried the SSAO (classic, etc), but it crashes (Mapple v2.5.2 on Win10 ; provided binaries).

Here is the mesh (STL file):
[thing_big.zip](https://github.com/LiangliangNan/Easy3D/files/11037849/thing_big.zip)

**Comment by LiangliangNan** [comment]
In the current implementation, the shadow plane is placed behind the object and it is orthogonal to the light direction:
![image](https://user-images.githubusercontent.com/15526536/226849834-817e13a4-599e-40ec-abeb-bda4aa1440a7.png)
For now, no UI or parameter is provided for a user to manipulate the shadow plane. But in case you want to play with it, please check and modify the code in  ` void Shadow::update_virtual_background()` in [shadow.cpp](https://github.com/LiangliangNan/Easy3D/blob/main/easy3d/renderer/shadow.cpp)

For the SSAO, does it also crash for any other models?

**Comment by yvanblanchard** [comment]
I checked on the fandisk_quads.off model, and the SSAO does work fine.

One other remark about shadow: It looks strange, since it's like the shadow is "around" the mesh, and not "projected" on a plane..
![image](https://user-images.githubusercontent.com/63931618/226853172-8f5f0a56-8ad5-49c5-b373-de5d9d71d9cb.png)

**Comment by LiangliangNan** [comment]
> I checked on the fandisk_quads.off model, and the SSAO does work fine.
I also tried to convert your model to another format (PLY). This conversion process also resolved the non-manifoldness in the model and it worked well. So I suspect that the non-manifoldness causes the crash. But I am quite sure. Wrote the code many years ago and couldn't think of the reason. I will look into the code later this month.

> One other remark about shadow: It looks strange, since it's like the shadow is "around" the mesh, and not "projected" on a plane.
It does project on a plane, but just that the plane is put behind the object (instead of serving as a "ground" plane). I may have some time this summer to improve this. Please also feel free to modify the code to have it.

**Comment by LiangliangNan** [comment]
ToDo:
- fix the bug where ambient occlusion crashes on non-manifold meshes
- provide options to support different types of shadow receiver planes

**Comment by yvanblanchard** [comment]
Hello,
Any updates for this ?
Thank you!

**Comment by LiangliangNan** [comment]
Finally, I had some time to fix the bug in ambient occlusion.
The reason was that normal information is not always available for points. 
You can test the latest code in the repository (but not in the Mapple executable) and let me know if you encounter any issue related to SSAO.

For the shadow, I will be working on it :-)
