### ISSUE TITLE
Addressing Non-Manifold Vertex Issues During Mesh Loading in OBJ format: 

### ISSUE THREAD

**Issue by WeixiaoGao** [LiangliangNan/Easy3D#169]
Hi,
Can We Preserve the Original Input Without Automatic Repair in OBJ format?
An example is attached [link](https://drive.google.com/file/d/11Kb4Wbj93R2-6asstvpV1UCLxWK3kCw2/view?usp=drive_link), where simply loading and saving the mesh both in OBJ format causes significant structural changes, which is undesirable."
![snapshot00_L00](https://github.com/LiangliangNan/Easy3D/assets/23455233/8b554489-7586-4642-8688-d31102acbd24)
![snapshot00_L01](https://github.com/LiangliangNan/Easy3D/assets/23455233/46e2fadb-7471-4d58-80eb-0235f13e2d3f)

**Comment by LiangliangNan** [comment]
Of course. You can create a very simple data structure to store the vertices and the vertex indices for each face. This data structure is very simple and direct for visualization. But it will be very challenge to use such a data structure to process/edit the model.

The structural change here is due to the HUGE coordinates of the vertices (compared to the very short edge lengths of many faces). Due to the limited precision of floating-point numbers, many faces become degenerated. So please don't take the "repair" wrong :-)
