### ISSUE TITLE
[Question]: Volumetric Rendering

### ISSUE THREAD

**Issue by jacquesvaneeden** [LiangliangNan/Easy3D#186]
For our current project we need to render some point cloud data attributes in different colours and transparency, as image below shows
Can Easy3D have an alpha / transparency per point? From examples provided I can only see colour  not transparency 

![Screenshot 2024-06-11 071159](https://github.com/LiangliangNan/Easy3D/assets/45024929/38273932-7c56-4aa6-a90a-562a657bb88b)

**Comment by LiangliangNan** [comment]
Currently, Easy3D doesn't support volumetric rendering. It is true that the rendering functionalities are not its strength, but many good open-source software packages (e.g., VTK) are handy to use. Since the purpose of this library is for fast prototyping of geometry processing algorithms (for meshes and point clouds), it is intended to keep it thin :-)
