### ISSUE TITLE
Question regarding primitive extraction

### ISSUE THREAD

**Issue by Sheradil** [LiangliangNan/Easy3D#190]
Hello,

I usually use Poisson Reconstruction to get meshes from point clouds, but at least in my opinion the poisson reconstruction fails to capture hard edges, like 90 degree angles present in houses, boxes etc.

One of my work students found the PolyFit paper and for our use case that looks very promising, because we mostly have sharp edges. 
Now I downloaded PolyFit and realized that I have to generate the bvg files before I can use PolyFit (as it does not allow ply files and can't generate the planes on it's own). Then I came here and it took some time to find the "RANSAC primitive extraction" which should give me the planes that I am looking for (am I correct?).
And the README of PolyFit says:
You can save the planes in bvg (Binary Vertex Group) format. The ASCII format vg also works but is slow. Please note, PolyFit assumes that the model is closed and all necessary planes are provided.

Now, my question is:
How do I save them so that I can use them in PolyFit?
Under File->Save I only have "Surface Mesh", "Point Cloud", "Polyhedral Mesh" and "Graph". To me that all seems to be the wrong option.

**Comment by LiangliangNan** [comment]
The "bvg" is a kind of point cloud, so you can use the point cloud option.

Best,
--
Liangliang
________________________________
From: Christopher ***@***.***>
Sent: Tuesday, July 30, 2024 7:21:37 PM
To: LiangliangNan/Easy3D ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LiangliangNan/Easy3D] Question regarding primitive extraction (Issue #190)


Hello,

I usually use Poisson Reconstruction to get meshes from point clouds, but at least in my opinion the poisson reconstruction fails to capture hard edges, like 90 degree angles present in houses, boxes etc.

One of my work students found the PolyFit paper and for our use case that looks very promising, because we mostly have sharp edges.
Now I downloaded PolyFit and realized that I have to generate the bvg files before I can use PolyFit (as it does not allow ply files and can't generate the planes on it's own). Then I came here and it took some time to find the "RANSAC primitive extraction" which should give me the planes that I am looking for (am I correct?).
And the README of PolyFit says:
You can save the planes in bvg (Binary Vertex Group) format. The ASCII format vg also works but is slow. Please note, PolyFit assumes that the model is closed and all necessary planes are provided.

Now, my question is:
How do I save them so that I can use them in PolyFit?
Under File->Save I only have "Surface Mesh", "Point Cloud", "Polyhedral Mesh" and "Graph". To me that all seems to be the wrong option.

**Comment by Sheradil** [comment]
Ok, makes sense.
Just expected different behaviour.

Thanks for your quick response

**Comment by Sheradil** [comment]
Thanks for your quick response.

Ok, that makes sense, I just expected different behaviour.
