### ISSUE TITLE
[BUG?] - [ERROR] unknown file format: bvg

### ISSUE THREAD

**Issue by Moondog-Bu** [LiangliangNan/Easy3D#192]
**Describe the bug**. 
I cannot save in .vg or .bvg format. The following error message appears.
[ERROR] unknown file format: bvg
[INFO] save model failed

**Tell us how to reproduce the bug**. 
Hello
I scanned a small faceted gemstone with our 3D scanner. The result is an STL file (STL attached).

I opened this STL in Mapple/Easy3D and switched on the points and normals. See "Image 01 & Image 02".

If I now click on save and enter e.g. Test.vg or Test.bvg as the file name and click on save, the error message appears.

I suspect I'm still doing something wrong or it's perhaps a bug.

Unfortunately, I haven't found any step-by-step instructions on how to create the required point cloud for your great tool "PolyFit" from an STL file.

The only thing I found is: "After you load the point cloud to Mapple, go to 'Partition' menu and click 'Extract Primitives'. To visualize the planes, change the renderer from 'Plain' to 'Group' in the Rendering panel (at the left side of Mapple). You can save the planes as bvg (Binary Vertex Group) format. The ASCII format vg also works but slow."

But I can't find a partition menu in Mapple and I only have the STL from the scanner, not a point cloud. However, the scanner also generates a "RawData" folder with various files in .ac format and a file in .asc format. I assume that these are the individual scans of the views and the summary of these. Maybe you can do something with these?

My goal is to then use "PolyFit" to recreate the surfaces (facets) of the scanned gemstone and end up with Nurbs surfaces. Is that possible?

Is there documentation/instructions somewhere that describes the functions of the many menu items?

Thank you for your time, I would be very happy to receive a tip.

Regards, Bruno

**Development/Running environment:**
 - OS: Windows 10,
 - Mapple (64 bit) Version 2.5.3 (based on Qt v5.15.2)
 - PolyFit (64-bit)

**Additional context**. 

![Image 01](https://github.com/user-attachments/assets/0131eaba-2d23-459f-9fff-2dc2e5c7251d)
![Image 02](https://github.com/user-attachments/assets/ff754f9c-aa3e-4750-b5bf-f91de98e5f02)
[STL.zip](https://github.com/user-attachments/files/16872828/STL.zip)

**Comment by LiangliangNan** [comment]
Only point clouds can be saved into vg or bvg format (after segmentation or primitive extraction).
Your input STL file is a surface mesh, not a point cloud. You can convert it into a point cloud (many ways: extract only the vertices, or sample the surfaces), but this is not necessary because you scanner should originally acquire a point cloud from which the STL mesh is reconstructed.

Best,
--
Liangliang
________________________________
From: Moondog-Bu ***@***.***>
Sent: Wednesday, September 4, 2024 5:01:22 PM
To: LiangliangNan/Easy3D ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LiangliangNan/Easy3D] [BUG?] - [ERROR] unknown file format: bvg (Issue #192)


Describe the bug.
I cannot save in .vg or .bvg format. The following error message appears.
[ERROR] unknown file format: bvg
[INFO] save model failed

Tell us how to reproduce the bug.
Hello
I scanned a small faceted gemstone with our 3D scanner. The result is an STL file (STL attached).

I opened this STL in Mapple/Easy3D and switched on the points and normals. See "Image 01 & Image 02".

If I now click on save and enter e.g. Test.vg or Test.bvg as the file name and click on save, the error message appears.

I suspect I'm still doing something wrong or it's perhaps a bug.

Unfortunately, I haven't found any step-by-step instructions on how to create the required point cloud for your great tool "PolyFit" from an STL file.

The only thing I found is: "After you load the point cloud to Mapple, go to 'Partition' menu and click 'Extract Primitives'. To visualize the planes, change the renderer from 'Plain' to 'Group' in the Rendering panel (at the left side of Mapple). You can save the planes as bvg (Binary Vertex Group) format. The ASCII format vg also works but slow."

But I can't find a partition menu in Mapple and I only have the STL from the scanner, not a point cloud. However, the scanner also generates a "RawData" folder with various files in .ac format and a file in .asc format. I assume that these are the individual scans of the views and the summary of these. Maybe you can do something with these?

My goal is to then use "PolyFit" to recreate the surfaces (facets) of the scanned gemstone and end up with Nurbs surfaces. Is that possible?

Is there documentation/instructions somewhere that describes the functions of the many menu items?

Thank you for your time, I would be very happy to receive a tip.

Regards, Bruno

Development/Running environment:

  *   OS: Windows 10,
  *   Mapple (64 bit) Version 2.5.3 (based on Qt v5.15.2)
  *   PolyFit (64-bit)

Additional context.

Image.01.jpg (view on web)<https://github.com/user-attachments/assets/0131eaba-2d23-459f-9fff-2dc2e5c7251d>
Image.02.jpg (view on web)<https://github.com/user-attachments/assets/6ab302af-17fb-415c-9ac8-0f1611360358>
STL.zip<https://github.com/user-attachments/files/16872828/STL.zip>

**Comment by Moondog-Bu** [comment]
Wow, thank you so much for your time and great help and for sharing your wonderful work.

After following your instructions, it now works wonderfully. Now I can play around with the parameters and see what happens.
I will look into your tools more closely to better understand what exactly the functions behind them are.
But I am already able to work with them, thanks to your help.

I hope that our dialogue will also be of valuable help to other users.

Bruno
