### ISSUE TITLE
line width

### ISSUE THREAD

**Issue by alior101** [LiangliangNan/Easy3D#20]
Hi,
Is there a support for other than default line width 1.0f ? 
I tried adding glLineWidth support to drawable.cpp but opengl complained for invalid value ..
Thanks

**Comment by LiangliangNan** [comment]
`glLineWidth` is almost useless in the modern OpenGL rendering pipeline. Changing the linewidth this way may not take effect because "Only width 1 is guaranteed to be supported" (in the OpenGL specification). The modern OpenGL uses geometry shader to achieve this for better performance.
To do this, you need to write geometry shader (i.e., modify the *.frag files). east3d will support this in a future release.

**Comment by LiangliangNan** [comment]
Hi, now you can tune line width using `LinesDrawable::set_line_width(float w)`.
Check `Tutorial_401_Drawable`. Press `w` (to show the wireframe of the mesh). Then press "+" or "-" to see the effect,

To visualize thicker lines, Easy3D now also provides you another option: draw lines as cylinders (or cones)> Please check `Tutorial_404_Imposters`.

Now I will close this issue. Please let me know if you any questions.

**Comment by alior101** [comment]
Thanks!
