### ISSUE TITLE
Unable to set the one color for single face

### ISSUE THREAD

**Issue by MichaelChen77** [LiangliangNan/Easy3D#83]
Hi Liangliang,

1, In Mapple viewer, I tried your advice and add a per face color attribute or a per face integer attribute. However, the face doesn't display any change. it still display the same color as "uniform color".
What I want to do is to add a double/float value to the face's attribute(example: auto face_attribute_ = mesh->face_property<double>("f_attribute_name") ). Then the viewer should displace each single face with the same color.
I also tried add a vec3 value as the color to the face's attribute (example: auto face_attribute_ = mesh->face_property<vec3>("f_attribute_name")). And again nothing happened.

Previously, I add a double/float value to the vertex's attribute(example: auto vertex_attribute_ = mesh->vertex_property<double>("v_attribute_name") ). But it can't make the single face with the same color. The face color is decided by it's 3 vertices's scalar value.

2, In Mapple, may I know what's the usage of "clamp" attribute in the surface panel? By default it's range are 5% and 5%. I am still a bit confused with the usage of this attribute during rendering.

Thanks!

Best regards
Yihao

**Comment by LiangliangNan** [comment]
Face properties are always start with "f:", e.g., f:color, f:my_color, f:normal.
Vertex properties are always start with "v:", e.g., v:color, v:my_color, f:normal.
Edge properties are always start with "e:", e.g., e:color, e:my_color, e:weight
...

### If you use Mapple
If the attributes are stored in a file, after you load it to Mapple, you should be able to change the visualized in the rendering panel. By default it is "uniform color", but you can choose the available attribute or scalar field for visualization.

### If you write your code
Adding a per-face color can be done by
`auto colors = mesh->face_property<vec3>(color_name); `
But now, all faces have the default same color, you should actually assign each face the expected color, e.g., 
`for (auto f : mesh->faces()) 
       colors = compute_color(f);    // not each R, G, B must be in the range [0.0, 1.0]
`
Then tell the rendering to use the available color attribute by
`  auto faces = mesh->renderer()->get_triangles_drawable("faces");
    faces->set_property_coloring(State::FACE, color_name);
    mesh->renderer()->update();
    viewer()->update();
`

"clamp" is used to handle outliers. Assume you have a scalar field with a value range [0, 100],  but due to some reasons (outlier or noise), one element has a value of 500. This will completely ruin the visualization because all other elements can only use a very small color range so the visualization can hardly differentiate their differences. The "clamp" percentage of elements are treated as outliers and the values are clamped.

For more details, see the documentation of the State class (easy3d/renderer/state.h).

**Comment by MichaelChen77** [comment]
Thanks for the detailed reply!
I tried the method according to your reply following:
"Adding a per-face color can be done by
auto colors = mesh->face_property<vec3>(color_name);
But now, all faces have the default same color, you should actually assign each face the expected color, e.g.,
for (auto f : mesh->faces()) colors = compute_color(f); // not each R, G, B must be in the range [0.0, 1.0]
Then tell the rendering to use the available color attribute by
auto faces = mesh->renderer()->get_triangles_drawable("faces"); faces->set_property_coloring(State::FACE, color_name); mesh->renderer()->update(); viewer()->update();"
And it works. To make it clear, I need to set color_name **prefix with "f:color"**, example: 
auto colors = mesh->face_property<vec3>("f:color_mycolor_name");

However in my project, there are some outliers which may strongly affect the face color. With the help of "clamp" function you mentioned, we can display the vertex color more properly. In addition, using different textures provided in the "Scalar Field", we can further display the result better.
This is the reason why I want to know if there is any method, which only sets/changes the scalar values assigning to face. Then per-face color can display according to this scalar value, which is similar to the per-vertex color. Eg: Can "auto face_colors = mesh->face_property<double>(face_color_scalar);" has similar/same result to "auto vertex_colors = mesh->vertex_property<double>(vertex_color_scalar);" In this way, we can further change the per-face color by modifying the "clamp" and "Scalar Field" 

Thanks!

**Comment by LiangliangNan** [comment]
I don't understand what you mean :-(
For your "sets/changes scalar values", you simply do, e.g. 

`curvature[v] = 0.34;`.    // v is a vertex
or
`importance[f] = 0.9;`.   // f is a face

You can simply provide a scalar value or color to each element (either a face or a vertex), then Easy3D will visualize them for you.
 - If you give each element a color, the colors are shown as is.
 - If you give each element a scalar value, the additional option 'clamp' is available for you to clamp the data, which makes it robust to outliers and noisy data.

**Comment by MichaelChen77** [comment]
Sorry for my bad expression. 

What I did is exactly the same as you mentioned above:
importance[f] = 0.9;. // f is a face
And this didn't give me the correct result. 

Now I finally understand how to use it:
When providing a scalar value to a face, the face preperty name should start with "f:", but don't start with "f:color", which will result that easy3d regards this property as a vec3 preperty.
When providing a vec3 value to a face (the value is vec3(r,g,b)), the face preperty name should start with "f:color". This vec3 value will directly set the per-face color.

Thanks again for your kindly reply and help!

**Comment by LiangliangNan** [comment]
No worries.
In Easy3D, colors, normals, and point coordinates use the same type 'vec3'. From the type of a property, it is not possible to say if it represents a color, normal, or 3D coordinates. That is why Easy3D depends on the name of properties.
